---
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dbOiControlePegasus
    username: user
    password: pass
    driver-class-name: org.h2.Driver

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.liquibase-diff-changeLog.yaml

server:
  port: 8080
  tomcat:
    internal-proxies: .*
  use-forward-headers: true
